# Generated by Django 4.0.5 on 2022-06-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_features_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Features',
        ),
    ]
